// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzZI0lCqTzxmgRUW9M7_R-fRVHDWUwHGc',
    appId: '1:759132227338:web:ea6ac1c91377e04d9b1cf3',
    messagingSenderId: '759132227338',
    projectId: 'eduai-844f7',
    authDomain: 'eduai-844f7.firebaseapp.com',
    storageBucket: 'eduai-844f7.firebasestorage.app',
    measurementId: 'G-10TCQR63BN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9SobBSXsDqbvGPVaYDjWZSjzeokEegUA',
    appId: '1:759132227338:android:1500637da2f1423d9b1cf3',
    messagingSenderId: '759132227338',
    projectId: 'eduai-844f7',
    storageBucket: 'eduai-844f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC-bNDYNGiVhEGet0ri3juZeqKW7KduZM',
    appId: '1:759132227338:ios:572b2f9e3f9a30299b1cf3',
    messagingSenderId: '759132227338',
    projectId: 'eduai-844f7',
    storageBucket: 'eduai-844f7.firebasestorage.app',
    iosBundleId: 'com.eduai.eduAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC-bNDYNGiVhEGet0ri3juZeqKW7KduZM',
    appId: '1:759132227338:ios:572b2f9e3f9a30299b1cf3',
    messagingSenderId: '759132227338',
    projectId: 'eduai-844f7',
    storageBucket: 'eduai-844f7.firebasestorage.app',
    iosBundleId: 'com.eduai.eduAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzZI0lCqTzxmgRUW9M7_R-fRVHDWUwHGc',
    appId: '1:759132227338:web:deac774eaa87ba729b1cf3',
    messagingSenderId: '759132227338',
    projectId: 'eduai-844f7',
    authDomain: 'eduai-844f7.firebaseapp.com',
    storageBucket: 'eduai-844f7.firebasestorage.app',
    measurementId: 'G-BE98SN4R38',
  );
}
